#!/usr/bin/expect
spawn adduser byhuang
expect "Enter new UNIX password:"
send -- "0000\r"
expect "Retype new UNIX password:"
send -- "0000\r"
expect "Full name \[\]:"
send -- "Bo-Yuan Huang\r"
expect "Room Number \[\]:"
send -- "\r"
expect "Work Phone \[\]:"
send -- "\r"
expect "Home Phone \[\]:"
send -- "\r"
expect "Other \[\]:"
send -- "\r"
expect "Is the information correct?"
send -- "Y\r"
expect eof

